In [1]:
# import numpy library
import numpy as np

In [2]:
# Create two square matrix
x = np.array([[1,5,6],[8,5,9],[1,0,3]])
z = np.array([[12,20,-3],[5,-8,5],[6,9,17]]) 
print(x,'\n')
print(z)

[[1 5 6]
 [8 5 9]
 [1 0 3]] 

[[12 20 -3]
 [ 5 -8  5]
 [ 6  9 17]]


In [3]:
#Add and sustract the matrices X and Z
r_added = x.__add__(z)
r_sustract = x.__sub__(z)
print(r_added,'\n')
print(r_sustract) 

[[13 25  3]
 [13 -3 14]
 [ 7  9 20]] 

[[-11 -15   9]
 [  3  13   4]
 [ -5  -9 -14]]


In [4]:
#pieceswise multiplication and Multiplication of two matrices
r_piecewise = x.__mul__(z)
r_mul = x.__matmul__(z)
print(r_piecewise,'\n')
print(r_mul)

[[ 12 100 -18]
 [ 40 -40  45]
 [  6   0  51]] 

[[ 73  34 124]
 [175 201 154]
 [ 30  47  48]]
